language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose --features 'dbus'

matrix:
  allow_failures:
    - rust: nightly

# DBUS on default env is too old

sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libdbus-1-dev
