language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  include:
    - script: cargo build --verbose
    - script: cargo build --verbose --features 'dbus'
