error_strategy = "abort"
# error_strategy = "continue"

overwrite_strategy = "skip"
# overwrite_strategy = "overwrite"

power_off = false
# power_off = true

[transfer_order]
download_directory = "transfer_order/"

[incremental]
download_directory = "incremental/"

# [wifi]
# ssid = "E-M10MKII-P-BHLA00000"
# interface = "wlp3s0"
