error_strategy = "abort"
# error_strategy = "continue"

overwrite_strategy = "skip"
# overwrite_strategy = "overwrite"

[transfer_order]
download_directory = "transfer_order/"

[incremental]
download_directory = "incremental/"
